### ISSUE TITLE
[Frontend] Use GenerateName instead of Name in resource templates

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#166]
# Problem
Duplicate auto-completed resource names on new.
(I don't know whether it is called `auto-complete`.)

e.g.)
- Create `New Pod`. (the pod name will be `pod1`.)
- Create `New Pod`.(the pod name will be `pod2`.)
- Delete `pod1`.
- Try to create `New Pod`. (the name will be `pod2`) ← `pod2` already exists.

**Comment by sanposhiho** [comment]
/retitle [Frontend] Use GenerateName instead of Name in resource templates

https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/web/components/lib/templates

**Comment by aibarbetta** [comment]
Hi all, is this a good first issue? If so, can you tell me a little more about what needs to be done? I see the use of name instead of generateName here https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/77a0cc568cdaa536ff1bc9c88f1ce9947ec60185/web/components/lib/template.ts#L14 but do you also want to start using hashes here https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/77a0cc568cdaa536ff1bc9c88f1ce9947ec60185/web/components/ResourceAddButton.vue#L105 instead of numbers that could collision?

**Comment by sanposhiho** [comment]
@aibarbetta 

Yes, it's easy one.
Feel free to assign yourself. (You can assign yourself to this issue by commenting `/assign`.)

We have templates for each resources:
https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/web/components/lib/templates

And, as you found, the name is shown by adding suffix, the current number of resources, to the name.
I guess all we need to resolve this issue is to remove those adding suffix implementation and change the templates to use GenerateName (instead of Name).

**Comment by aibarbetta** [comment]
Thanks @sanposhiho!
/assign
