### ISSUE TITLE
Integrate kwok into simulator

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#251]
In the simulator, we just run almost pure kube-apiserver. The simulator doesn't have much controllers, and something seems actually weird to users sometimes. (like some fields in Pods and Nodes don't get changed, etc)
And, for example, https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/243 directly affects the scheduling results, which we must avoid as a simulator. 

I feel we can almost resolve them by integrating [Kwok](https://github.com/kubernetes-sigs/kwok) which watches Node and Pods and behaves like kubelet. We can expect Pods and Nodes to behave more like a real cluster but without running any real instances or containers.

/kind feature
/triage accepted
/area simulator
/priority important-longterm

**Comment by wzshiming** [comment]
Cool, I think the cluster created by `kwokctl` should not start the scheduler and `kube-scheduler-simulator` should take care of the scheduling, so that kwok should be able to be integrated. What do you think?

**Comment by sanposhiho** [comment]
> kwokctl should not start the scheduler and kube-scheduler-simulator should take care of the scheduling

Yes. In other words, I feel the simulator should depend on all other parts like running controller-manager, kube-apiserver, etc. 
Once kwokctl gets the ability to disable scheduler, we can refactor the simulator's scheduler to run on top of kwok, and this repository can focus on the simulating related stuff.

**Comment by sivchari** [comment]
I'm interesting at this issue. If you would like, I would like discuss the integration, too.

**Comment by wzshiming** [comment]
I'm back, sorry for the wait 🙏.
[The Kwok v0.1.0](https://github.com/kubernetes-sigs/kwok/releases/tag/v0.1.0) has been released, which supports the ability to disable the default scheduler, and an all-in-one image that I particularly like.

## Use all-in-one image create cluster

``` bash
docker run --rm -it --env KWOK_DISABLE_KUBE_SCHEDULER=true  -p 8080:8080 registry.k8s.io/kwok/cluster:v1.26.0
```

## Use kwokctl create cluster

``` bash
kwokctl create cluster --disable-kube-scheduler=true
```

**Comment by sanposhiho** [comment]
Thanks @wzshiming for sharing. 
One thing to confirm, does Kwok support the CRD? I mean, can we use CR as a usual kube-apiserver when we apply CRD on Kwok?

**Comment by wzshiming** [comment]
Of course, it is used just like a normal cluster.

**Comment by sanposhiho** [comment]
Great. I discussed with @196Ikuchil and sum up our thought on this migration, here is the summary.

From now on, the simulator _completely_ removes the kube-apiserver in it and requires users to start up kube-apiserver by themselves. In the documentation, we'd recommend using Kwok. (Of course, the simulator can be used with other kube-apiservers, we probably can prepare other ways like minikube, Kind etc if there is an usecase.)

This migration is worthwhile not only for the simulator users, but also for maintainers, because we no longer need to maintain the kube-apiserver related codes and we can just focus on the scheduler-simulation related stuff. Especially, the scheduler simulator is currently short on maintainers, we'd love to maintain as minimum things as possible to make a big value.

The tasks on it are:
- [ ] make our simulator to be able to disable the kube-apiserver and all controllers in it with the deprecation notice.
- [ ] revise README.md to use the simulator with Kwok. Disable kube-apiserver in the simulator + use Kwok instead.
- [ ] [after a few months] remove the kube-apiserver and all controllers in the simulator.

**Comment by 196Ikuchil** [comment]
Awesome👍 
This change makes kube-scheduler-simulator a tool more dedicated to testing and debugging tasks related to scheduling!

**Comment by sivchari** [comment]
It's great works for us 👍 
This chages help users and maintainers !
I want to contribute this migrations 😸 
I would like to work to improve the kube-scheduler-simulator !

**Comment by sanposhiho** [comment]
@sivchari Do you still plan to work on it? or want anyone to take over it?

**Comment by sivchari** [comment]
@sanposhiho 
Sorry, I'll work on it.

**Comment by sanposhiho** [comment]
/priority next-release

@sivchari 
Let's make it done within the next release.

**Comment by sanposhiho** [comment]
/remove-assign @sivchari 
/assign @sanposhiho 

I talked with @sivchari and he said no time to work on for a while. I'll take over this one.

**Comment by sivchari** [comment]
@sanposhiho 

Hi, I can have time to try this. So Can I try this ?
/assign @sivchari

**Comment by sivchari** [comment]
I've read this conversation again. I propose a solution I think.
1. Add new configuration value named Kube API Server URL.
2. If this value is empty, kube-scheduler-simulator create a Kubernetes API Server. If not, kube-scheduler-simulator skips to create it.
3.  Update the README.md to use the simulator with another Kubernetes API Server. (Recommending Kwok)
4. After a few months, remove the kube-apiserver and all controllers in the simulator.

Fist, I work until step 2.

**Comment by 196Ikuchil** [comment]
@sivchari 
Hi, Sorry for late.
Please take it on. I

I have taken on this one, and in fact, the implementation of the simulator was almost complete, but I left it alone as I was struggling with the policy of modifying the WebUI.

So I would like to offer some advice.

1. To connect to kwok's api-server, the kubeconfig file must be passed to simulator via an environment variable when launching it.
- Unfortunately, kubeconfig is currently designed to reference ExternalResource imports, so it needs to be modified to consider them.
- There is some unnecessary code mixed in, but it is code I created previously. You can take a look at it for reference if you like.
  -  Ref: https://github.com/196Ikuchil/kube-scheduler-simulator/pull/1
2. We need to rethink the design for using the WebUI. 
- WebUI also needs kubeconfig information to connect to kwok. This is because WebUI currently calls the api-server URL directly from the application in the browser.
- We have several ideas to solve these problems.
  - 1. The WebUI connects to the api-server (kwok) via an endpoint provided by the simulator server, which can be achieved by diverting the kubeconfig loaded when launching simulator. But we need to re-implement the kind of service that was previously deprecated. https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/305
  - 2. A new endpoint is implement on the WebUI server, and the application on the browser connects to kwok via that endpoint. kubeconfig is loaded when webUI is launched.
  - 3. Make sure to call api-server directly from the app in the browser. (This is the current method.) From what I have found, this seems difficult to achieve with the [client library](https://www.npmjs.com/package/@kubernetes/client-node)

Please ask any questions you may have!

**Comment by 196Ikuchil** [comment]
Hi, there!
I have been away for a while.

I will start working on the webUI fixations for now.
Below is a diagram of what I consider As-Is and To-Be. (This may not be an accurate 😅)

![diagram](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/22634362/6d066586-d089-4120-a67d-a41229fbc41e)

Since kwok's api-server is of course protected by access control, we need to pass the authentication information(kube-config data) to the webUI somehow.

I am planning to implement this with a **plan A**.
If this could be done, the amount of fixations would be very small and the code would remain concise, since it would be possible to invoke the api-server endpoint directly, without changing the current implementation.
Authentication data can be obtained by `kwokctl get kubeconfig`, so we will consider a mechanism to make it as easy as possible for users to input the data.

If the above plan is not feasible, we will attempt **Plan B**.
The plan uses [kubernetes-client](https://github.com/kubernetes-client/javascript) on the WebUI server to communicate with api-server. kube-config is also automatically loaded at the server launch.
However, since the WebUI server exists as a proxy between the browser and the api-server, it may be necessary to have the same number of RESTful endpoints implemented as the api-server. 
Code management for the WebUI will also be difficult. This is a huge disadvantage.

**Comment by 196Ikuchil** [comment]
/assign

on WebUI work

**Comment by sivchari** [comment]
Sorry for the late reply.

Plan B looks good to me, too.

> If the above plan is not feasible, we will attempt Plan B.
The plan uses [kubernetes-client](https://github.com/kubernetes-client/javascript) on the WebUI server to communicate with api-server. kube-config is also automatically loaded at the server launch.
However, since the WebUI server exists as a proxy between the browser and the api-server, it may be necessary to have the same number of RESTful endpoints implemented as the api-server.
Code management for the WebUI will also be difficult. This is a huge disadvantage.

I don't understand why `plan B` need to have the same number of HTTP endpoints. I think WebUI doesn't worry if a kube-api-server is contained in WebUI Server (It's a simulator-server, right ?) or external component. If so, I think `plan B` is better than `plan A`. What do you think ?

**Comment by wzshiming** [comment]
> @wzshiming I may have already asked this in a different place though, do you see any way that allows us using Kwok internally? I mean by "internally" that the simulator internally uses Kwok to run up kube-apiserver etc, and users don't need to install Kwok on their laptops.


I think it is possible to use the `kwokctl` to manage the cluster in the simulator itself, like [kubernetes-sigs/e2e-framework/support/kwok](https://github.com/kubernetes-sigs/e2e-framework/blob/c61338a3773c2b64550d0e46037bfe541fa54645/support/kwok/kwok.go#L135)

**Comment by 196Ikuchil** [comment]
@sivchari 
> I don't understand why plan B need to have the same number of HTTP endpoints.

Thank you!
For example. if you implement new endpoints to create/list/delete  pod. You may need these on webUI server.
- GET `webuihost/api/v1/namespaces/:namespace:/pods`
- POST `webuihost/api/v1/namespaces/:namespace:/pods`
- DELETE `webuihost/api/v1/namespaces/:namespace:/pods/:pod:`

We need to implement as many resources as webUI handles.


@ here

But, I recently realized that planB may have advantages over it 👀 
The As-Is diagram posted previously had an error in the `watch` path. In fact, the `watch` is invoked via the watch endpoint launched by the kube-scheduler-simulator binary. This is the same for the `export`, `import` features, too.
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/22634362/559b5f97-fd7a-4170-9e05-1f2633d15cff)

These features can be achieved through communication just between api-server and webUI-server when planB is.
I think, there is no particular reason to go through the binary launched by kube-scheduler-simulator, and it seemed simpler to integrate export/import functions, etc. as a webUI server function. (It would also be convenient to specify clusters to be imported from the webUI side.)


What do you think?

**Comment by 196Ikuchil** [comment]
>  I mean by "internally" that the simulator internally uses Kwok to run up kube-apiserver etc, and users don't need to install Kwok on their laptops.

Certainly this one is important..
This is a bit related to my post above, but it is nice to be able to manipulate the kwok internally, since the `reset` function is currently achieved by restarting the api-server.

**Comment by sanposhiho** [comment]
> I think it is possible to use the kwokctl to manage the cluster in the simulator itself, like [kubernetes-sigs/e2e-framework/support/kwok](https://github.com/kubernetes-sigs/e2e-framework/blob/c61338a3773c2b64550d0e46037bfe541fa54645/support/kwok/kwok.go#L135)


@wzshiming Doesn't that require users to install `kwokctl`? Can't we import `kwokctl` package (or maybe something in kwok) in the simulator and directly call the logic of kwokctl without `kwokctl` binary?

**Comment by wzshiming** [comment]
> > I think it is possible to use the kwokctl to manage the cluster in the simulator itself, like [kubernetes-sigs/e2e-framework/support/kwok](https://github.com/kubernetes-sigs/e2e-framework/blob/c61338a3773c2b64550d0e46037bfe541fa54645/support/kwok/kwok.go#L135)
> 
> @wzshiming Doesn't that require users to install `kwokctl`? Can't we import `kwokctl` package (or maybe something in kwok) in the simulator and directly call the logic of kwokctl without `kwokctl` binary?

You can indeed call kwokctl directly to manage the cluster logic, but since there are still quite a few new features being developed, I can't be sure of compatibility at the code level. Still, compatibility at the command level is easier to do.

In `kubernetes-sigs/e2e-framework` if it doesn't exist in GOPATH, then [go build](https://github.com/kubernetes-sigs/e2e-framework/blob/c61338a3773c2b64550d0e46037bfe541fa54645/support/kwok/kwok.go#L71) it in code and use the binary from the build.

**Comment by 196Ikuchil** [comment]
> In kubernetes-sigs/e2e-framework if it doesn't exist in GOPATH, then [go build](https://github.com/kubernetes-sigs/e2e-framework/blob/c61338a3773c2b64550d0e46037bfe541fa54645/support/kwok/kwok.go#L71) it in code and use the binary from the build.

Thank you! Looks great 👍 

@wzshiming
Could I ask one question?
Is it possible to get the `kubeconfig` of the cluster created by the `kwokctl create cluster` command in advance, or could we specify it before creation?
The WebUI we provide requires the certificates, key, and others listed in kubeconfig in order to access the api-server directly from the browser.

On my terminal, I was able to get the credentials to the created cluster by doing `kwokctl get config` command, but if uses the binary from the build?
It requires us to implement an API in the simulator that exposes the credentials of the cluster generated by the simulator? (or always communicate through the simulator server.)

**Comment by wzshiming** [comment]
@196Ikuchil

> Is it possible to get the kubeconfig of the cluster created by the kwokctl create cluster command in advance, or could we specify it before creation?

Its path can be specified, but the content is not possible at the moment, as the certificates are randomly generated.


> The WebUI we provide requires the certificates, key, and others listed in kubeconfig in order to access the api-server directly from the browser.

Maybe I think there's a way to get around this, use [`kwokctl kubectl proxy --port="${KWOK_KUBE_APISERVER_PORT}" --accept-hosts='^*$' --address="0.0.0.0"`](https://github.com/kubernetes-sigs/kwok/blob/a5b7f72fbdf83a49c0b39fc393f7d4e4b76653cf/images/cluster/entrypoint.sh#L57)

This is an example of kwok exposing apiserver with http in an all-in-one image
https://kwok.sigs.k8s.io/docs/user/all-in-one-image/

**Comment by 196Ikuchil** [comment]
@wzshiming 
I see, thank you!

@sanposhiho 

> Maybe I think there's a way to get around this, use [kwokctl kubectl proxy --port="${KWOK_KUBE_APISERVER_PORT}" --accept-hosts='^*$' --address="0.0.0.0"](https://github.com/kubernetes-sigs/kwok/blob/a5b7f72fbdf83a49c0b39fc393f7d4e4b76653cf/images/cluster/entrypoint.sh#L57)

Do you think using the `proxy` command and exposing it will have any problems or negative effects on the simulator?
I think there do not seem to be any problems. This is because it does not require any new operations for the user to connect with the simulator.

**Comment by sanposhiho** [comment]
Yep, we can explore that idea and re-discuss if something doesn't work.

**Comment by sivchari** [comment]
Sorry for late reply.  I found no problem to mind.
So,  I want to discuss about the specific design to integrate kwok.
We will decide to simulator uses kwok internally, right ?

**Comment by 196Ikuchil** [comment]
> We will decide to simulator uses kwok internally, right ?

Yes. I think we will(maybe) launching kwok instead of  [api-server or controller around here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/4b0dd784a76edea312bb62427eddb57370800fb1/simulator/simulator.go#L38-L46).

**Comment by 196Ikuchil** [comment]
And, if we use `proxy` to expose the server, we don't need to fix the webUI because the access method is still the same as the current one.

**Comment by sivchari** [comment]
Sorry for the late reply. I have a one question about proxy.
`simulator` executes `kwokctl kubectl proxy --port="${KWOK_KUBE_APISERVER_PORT}" --accept-hosts='^*$' --address="0.0.0.0"`, right ?
If so, I think `simulator` should install kwokctl and kubectl.  If not, is there a better way ?
Thanks.

**Comment by wzshiming** [comment]
Your understanding is right, `kwokctl` will try to install `kubectl` if it doesn't exist, so just need to install kwokctl and we can [download binary release](https://kwok.sigs.k8s.io/docs/user/installation/#install-kwokctl) or use [go install sigs.k8s.io/kwok/cmd/kwokctl@v0.4.0](https://kwok.sigs.k8s.io/docs/user/installation/#install-with-golang)

**Comment by wzshiming** [comment]
Another idea, add [kwok all in one cluster image](https://kwok.sigs.k8s.io/docs/user/all-in-one-image/) in to the [docker-compose.yml](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/docker-compose.yml)

**Comment by wzshiming** [comment]
I gave it a try, and the simplest integration could be achieved with a shared etcd.

```yaml
version: "3.7"
services:
  simulator-server:
    image: registry.k8s.io/scheduler-simulator/simulator-backend:v0.1.1
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-cluster:2379
      - CORS_ALLOWED_ORIGIN_LIST=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3000
      - KUBE_API_HOST=0.0.0.0
      - KUBE_API_PORT=3131
    ports:
      - "1212:1212"
      - "3131:3131"
    restart: always
    tty: true

  simulator-frontend:
    image: registry.k8s.io/scheduler-simulator/simulator-frontend:v0.1.1
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3131
    ports:
    - "3000:3000"
    tty: true

  simulator-cluster:
    image: ghcr.io/wzshiming/kwok/cluster:v0.5.0-rc.4-k8s.v1.29.0
    container_name: simulator-cluster
    restart: always
    ports:
      - "8080:8080"
    command:
      - --etcd-prefix=/kube-scheduler-simulator
      - --etcd-port=2379
      - --disable-kube-scheduler
    environment:
      - KWOK_KUBE_APISERVER_PORT=8080
    volumes:
      - simulator-etcd-data:/var/lib/etcd

volumes:
  simulator-etcd-data:
```

**Comment by sanposhiho** [comment]
> no need to modify simulator's code.

That is not what we want to do. The simulator would still have a kube-apiserver (using a etcd shared with kwok) running in it.
Our biggest motivation here is to reduce the maintainance burden by replacing the implementation around kube-apiserver and the controllers in the simulator with kwok.

**Comment by sanposhiho** [comment]
So, after all I think the original idea that we discussed before would be a great fit here (if it works as we expect. At least, it's worth giving it a try.) -- use [kubernetes-sigs/e2e-framework/support/kwok](https://github.com/kubernetes-sigs/e2e-framework/blob/c61338a3773c2b64550d0e46037bfe541fa54645/support/kwok/kwok.go) plus use `kwokctl kubectl proxy...`.

**Comment by wzshiming** [comment]
I agree with you.

I looked at the simulator code, which could be a big change, especially the `Reset` function is operated on Etcd, and may not work with other vendors.

So I've come up with a smoother switch solution that allows it to slowly remove the Etcd and controllers and use the Apiserver.

**Comment by sivchari** [comment]
Hi, I opened [the new PR](#333) that tries to integrate kwok into simulator.
I described the purpose into it. 

Now, we can launch simulator server and web ui using kwok.
But web-ui cannot access the kube-apiserver because this pr cannot apply CORS to kube-apiserver. It is the cause of kwokctl doesn't have the flag about handling CORS. So I opened here about it.
In additional, `--etcd-prefix` can be used since v0.5.0 and e2e-framework can only download up to v0.3.0. So I opened this correction, too.

Thanks.

**Comment by wzshiming** [comment]
I have a quick question, why not do a reverse proxy for backends in the web, instead of using CORS?

**Comment by sivchari** [comment]
@wzshiming 

Thanks for your nice question.  I've forgotten using kubectl proxy.
I updated it. Now, we can access the api-server via proxy. In fact, I can succeed to request to create pod and list pods by curl.
web ui will be able to access, if kwokctl will be able to handle CORS setting later.

**Comment by sivchari** [comment]
> I think you can modify ~/.kwok/kwok.yaml to adapt.

It looks good to me.
Actually, when I did it in a state of mounting kwok.yaml, the simulator works completely.  I'm so happy to let you know about this integration.

https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/55221074/a7fd926b-1263-4732-9bc0-9b3d1e3ee988
